//Help buttons
function BtnHelp(){


    //Help buttons
    d3.select('#btnHelp_parcoords').on('click', function() 
      {swal({
        title: "Parallel coordinates plot",
        html: "<div style='text-align: left;'> Each vertical axis corresponds to an ES objective, each line represents a scenario. " +
                "The values plotted correspond to the overall aggregated objective score, for the scenario considered (i.e the sum of all pixels’ scores for this objective, across the raster)."
                + "<br/>" + 
                "<ul> <h3> ES objectives: </h3>  <li> <b> AWY: Annual water yield </b>in 10<sup>6</sup> m<sup>3</sup>/year </li> \
                <li> <b> SDE: Sediment export to stream </b>in 10<sup>6</sup> tons of sediments eroded annually</li>\
                <li> <b> SDL: Soil loss to stream </b>in 10<sup>6</sup> tons lost to stream annually</li> </ul>" + "<hr/>" +
                "<i> Features" +
                "<ul> <li> Select a subset of solution : by brushing on any axis </li> \
                <li> Flip axis direction: upon double clicking on their name </li>\
                <li> Re-order axis: by dragging them</li> </ul> </i> </div>" 
         }).catch(swal.noop);
    });


      
    d3.select('#btnHelp_sliders_ow').on('click', function() 
        {swal({
        title: "Objective weights sliders",
        html: "<div style='text-align: left;'> \
                The objective weights corresponds to the relative importance given to each ES objective in each run."  
                + "<br/>" + "<br/>" + "Different scenarios  were generated by varying the objective weights combination \
                (that always sums to 100% : e.g a run where each objective is given equal importance : <i> AWY_weigth = SDE_weight = SDL_weight = 33%). </i> \
                Here, 15 combinations of objective weights were generated." + "<br/>" + "<br/>" + 
                "<i> Slide to select a subset of scenarios, giving importance to specific objective(s)</i> </div>"
         }).catch(swal.noop);
    });



    d3.select('#btnHelp_sliders_pu').on('click', function() 
        {swal({
        title: "Key input parameters sliders",
        html:  "<div style='text-align: left;'> \
                Several model input parameters are subject to uncertainty.\
                To account for this, the model is run for several possible values of each uncertain parameter." + "<br/><br/>" 
                + "<ul> The uncertain model input parameters are : \
                <li> <b> seasonality factor, Z</b>, an empirical (unitless) constant used to calculate the AWY in the <a href='http://data.naturalcapitalproject.org/nightly-build/invest-users-guide/html/reservoirhydropowerproduction.html#summary'> InVEST annual water yield model</a>. It captures the local precipitation pattern and additional hydrogeological characteristics. </li> \
                <li> <b> soil erodibility value, K</b>, used to calculate the amount of annual soil loss in the <a href='http://data.naturalcapitalproject.org/nightly-build/invest-users-guide/html/sdr.html#summary'> sediment delivery ratio InVEST model </a> It measures the susceptibility of soil particles to detach and transport by rainfall and runoff. Unit is ton*ha*hr/(MJ*ha*mm). </li> \
                <li> <b> Spatial </b> corresponds to different biophysical table tables used. Terrestrial InVEST models require a biophysical table that maps values for various parameters to each land cover class. This allows to switch between the default “biophysical table” constructed for Tana (A), and one with alternate parameter settings (B). </li> \
                <li> <b> The budget level : this is not itself an uncertain parameter but rather a choice in the optimization. Currently three levels chosen for illustrative purposes (12.5, 25 and 37.5 M USD, presented in Kenyan Shillings at an exchange rate of 50 KSh:USD) </li> </ul>" + "<br/>" + "<br/>" + 
                "<i> Slide to select a subset of scenarios, according to specific values of these input parameters </i> </div>"
        }).catch(swal.noop);
    });

    d3.select("#btnHelp_scatterplots").on('click',function()
      {swal({
        title: "Trade-off curves",
        html: "<div style='text-align: left;'> \
              Tradeoff curves display the tradeoffs between each pair of ES objectives. \
              Each plotted point corresponds to a scenario." + "<br/>" + "<br/>" +
              "<i> The colorscale provides additional information about which value of some uncertain input parameters were used: \
              the orange points correspond to scenarios generated under the spatial scenario A, the blue ones under scenario B.\
              The color intensity gives an indication of the budget (a lighter color is a smaller budget).\
              <br/> Lines can be plotted, conecting the dots generated under the same combination of uncertain input parameters values. <i> </div>"

      }).catch(swal.noop);
    });

    d3.select("#btnHelp_map").on('click',function()
      {swal({
        title: "Map",
        html: "<div style='text-align: left;'> \
            Different types of maps combining information about the selected scenarios can be displayed, using the map control buttons on the upper left.\
            <br/> <ul> <h3> Portfolios </h3> \
            <li> <b> Portfolio </b>  map display the modal portfolio (= for each pixel, the most frequently selected intervention across scenarios selected). For the case of a single scenario display, it simply shows the corresponding portfolio. </li>\
            <li> <b>  Footprint map </b> reflects the areas selected consistenly for interventions, across several scenario. For the case of a single scenario display, it is just the overall footprint of its portfolio. </li>\
            <li> <b>  Agreement map </b> is an expression of the consistency between runs. It displays for each pixel, the % of scenarios in which the modal intervention was chosen <i>(modal intervention is the most chosen one, displayed on the modal portfolio). </i> It is not relevant for the case of a single scenario display. </li>\
            <li> <b>  Current land cover map </b>  shows the context. Any categorical map (such as a portfolio) may be overlayed on top. </li> </ul>\
            <br/> <ul> <h3> Objective score maps </h3> \
            <li> <b> Absolute objective score maps </b> for each ES objective, display the local objective scores averaged *averaged or summed bpb?* over the selected scenarios. </li> <li> <b> Marginal objective score maps </b>  corresponds to the change in objective score between the current situation (baseline) and the scenario considered. Therefore they are calculated as the difference between the absolute objective score map of the scenario, and the absolute objective score map of the baseline. </li> </ul>\
            <hr/><br/> The maps can be calculated from 3 distinct selection cases: \
            <ul> <li> <b>for all scenarios</b>: these map show results summarizing all scenarios. By default, they are displayed initially when no selection have occurred. </li> \
            <li> <b>for a subset of scenarios</b>: these map show results summarizing the scenarios selected through the other views. This situation occurs when the button <i> Calculate map for selection </i> is clicked. </li>\
            <li> <b>for a single scenario</b>: these maps displays the results corresponding to a specific solution; this occurs upon clicking on the corresponding scenario row in the data table. </li> </ul> \
            <hr/><br/> Map control buttons allow to pick the map to be displayed. The legend, as well as corresponding map summary statistics are computed and update automatically. The map window is enhanced with zooming abilities, upon click on the <i> Enable zooming </i> button. </div>"
      }).catch(swal.noop);
    });

        d3.select("#btnHelp_gnrl").on('click',function()
      {swal({
        title: "Optimization results for the Maragua watershed",
        html: "<div style='text-align: left;'> \
                <br/> \
                <ul> <h3> Ecosystem services (ES) objectives: </h3> <li> maximize annual water yield (AWY in 10<sup>6</sup> m<sup>3</sup>/year) </li> \
                <li> minimize sediment reaching streams (SDE in 10<sup>6</sup> tons of sediments eroded annually)</li>\
                <li> minimize soil loss for agricultural productivity (SDL) in 10<sup>6</sup> tons lost to stream annually)</li> </ul>" + 
                "<br/>" + "800 scenarios were generated, arising from parametric uncertainty (4 parameters with 2 to 4 possible values each)\
                and 15 combinations of objectives weights." +
                "<hr/>" + " <i> The full dataset table can be viewed. It is also linked to the other views: the dataset shrinks to match the selection when a subset of scenarios is chosen\
                (upon brush on the parallel coordinates plot, or a slide over a sub-range of the sliders for example). Upon click on a specific row, this solution is highlighted in all\
                plots (corresponding point in scatterplots, and line in parallel coordinates plot) and the maps corresponding to this scenario are displayed. </i> </div>"

      }).catch(swal.noop);
    });



}